version: '2'
services:

    gn:
        build: ./gn
        expose:
            - "8009"
        links:
            - db
        volumes_from:
            - data
        container_name: "geonetwork"

    gs:
        build: ./gs
        expose:
            - "8009"
        links:
            - db
        volumes_from:
            - data
        container_name: "geoserver"

    db:
        build: ./db
        volumes_from:
            - data

    apache:
        build: 
            context: ./httpd
        ports:
            - "80:80"
            - "443:443"
        container_name: "apache"

    pcapi:
        build:
            context: https://raw.githubusercontent.com/cobweb-eu/pcapi/master/docker/Dockerfile
        expose:
           - "8080"
        container_name: "pcapi"

    survey-designer:
        build:
            context: https://raw.githubusercontent.com/edina/survey-designer/master/docker/Dockerfile
        expose:
           - "80"
        container_name: "survey-designer"
        command: /usr/sbin/apache2ctl -D FOREGROUND

    data:
        build: ./data
